import{a as u,S as m,i as p}from"./assets/vendor-D9tHNiur.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();u.defaults.baseURL="https://pixabay.com";async function f(a,o=1,l=40){const s="https://pixabay.com/api/",e="49114756-3e4a97c2ae725133efe287d92";try{return await u.get(s,{params:{key:e,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:l}})}catch(r){throw console.error("Error fetching images:",r),r}}function h({webformatURL:a,largeImageURL:o,tags:l,likes:s,views:e,comments:r,downloads:i}){return`
    <li class="gallery-item">
        <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${a}" alt="${l}" />
        </a>
        <ul class="image-info">
            <li class="info-item"><p class="text">Likes</p><p class="text-value">${s}</p></li>
            <li class="info-item"><p class="text">Views</p><p class="text-value">${e}</p></li>
            <li class="info-item"><p class="text">Comments</p><p class="text-value">${r}</p></li>
            <li class="info-item"><p class="text">Downloads</p><p class="text-value">${i}</p></li>
        </ul>
    </li>
    `}const y=new m(".gallery a",{captionsData:"alt",captionDelay:250});function g(a){return a.map(h).join("")}const t={form:document.querySelector(".search-form"),input:document.querySelector("#image-input"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};let c="",n=1;const d=40;t.loadMoreBtn.style.display="none";t.form.addEventListener("submit",async a=>{if(a.preventDefault(),c=t.input.value.trim(),n=1,!!c){t.gallery.innerHTML='<span class="loader"></span>',t.form.reset(),t.loadMoreBtn.style.display="none";try{const{data:o}=await f(c,n,d);t.gallery.innerHTML="",o.hits.length?(t.gallery.innerHTML=g(o.hits),y.refresh(),n*d<o.totalHits&&(t.loadMoreBtn.style.display="block")):p.info({message:"Sorry, no images found. Try again!",backgroundColor:"#ef4040",position:"topRight"})}catch{p.error({message:"Something went wrong. Please try again later.",position:"topRight"}),t.gallery.innerHTML=""}}});t.loadMoreBtn.addEventListener("click",async()=>{n+=1,t.loadMoreBtn.disabled=!0,t.loadMoreBtn.innerHTML='<span class="loader"></span>';try{const{data:a}=await f(c,n,d);t.gallery.insertAdjacentHTML("beforeend",g(a.hits)),y.refresh();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),n*d>=a.totalHits&&(t.loadMoreBtn.style.display="none",p.info({message:"You've reached the end of search results.",position:"topRight"}))}catch{t.loadMoreBtn.style.display="none",p.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{t.loadMoreBtn.disabled=!1,t.loadMoreBtn.innerHTML="Load More"}});
//# sourceMappingURL=index.js.map
