import{a as d,S as y,i as p}from"./assets/vendor-D9tHNiur.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();d.defaults.baseURL="https://pixabay.com";async function f(s,r=1,l=40){const a="https://pixabay.com/api/",e="49114756-3e4a97c2ae725133efe287d92";try{return await d.get(a,{params:{key:e,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:l}})}catch(t){throw console.error("Error fetching images:",t),t}}function h({webformatURL:s,largeImageURL:r,tags:l,likes:a,views:e,comments:t,downloads:n}){return`
    <li class="gallery-item">
        <a class="gallery-link" href="${r}">
            <img class="gallery-image" src="${s}" alt="${l}" />
        </a>
        <ul class="image-info">
            <li class="info-item"><p class="text">Likes</p><p class="text-value">${a}</p></li>
            <li class="info-item"><p class="text">Views</p><p class="text-value">${e}</p></li>
            <li class="info-item"><p class="text">Comments</p><p class="text-value">${t}</p></li>
            <li class="info-item"><p class="text">Downloads</p><p class="text-value">${n}</p></li>
        </ul>
    </li>
    `}const g=new y(".gallery a",{captionsData:"alt",captionDelay:250});function m(s){return s.map(h).join("")}const o={form:document.querySelector(".search-form"),input:document.querySelector("#image-input"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};let c="",i=1;const u=40;o.loadMoreBtn.style.display="none";o.form.addEventListener("submit",async s=>{if(s.preventDefault(),c=o.input.value.trim(),i=1,!!c){o.gallery.innerHTML='<span class="loader"></span>',o.form.reset();try{const{data:r}=await f(c,i,u);o.gallery.innerHTML="",r.hits.length?(o.gallery.innerHTML=m(r.hits),g.refresh(),i*u<r.totalHits?o.loadMoreBtn.style.display="block":o.loadMoreBtn.style.display="none"):(p.info({message:"Sorry, no images found. Try again!",backgroundColor:"#ef4040",position:"topRight"}),o.loadMoreBtn.style.display="none")}catch{p.error({message:"Something went wrong. Please try again later.",position:"topRight"}),o.gallery.innerHTML=""}}});o.loadMoreBtn.addEventListener("click",async()=>{i+=1;try{const{data:s}=await f(c,i,u);o.gallery.insertAdjacentHTML("beforeend",m(s.hits)),g.refresh();const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*u>=s.totalHits&&(o.loadMoreBtn.style.display="none",p.info({message:"You've reached the end of search results.",position:"topRight"}))}catch{p.error({message:"Something went wrong. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
